### ISSUE TITLE
Use Flake 8 to test builds?

### ISSUE THREAD

**Issue by fralau** [fralau/mkdocs-macros-plugin#107]
In #106 it was proposed to use [Flake 8](https://flake8.pycqa.org/en/latest/).

___________
Just a question but would it be possible to get something simple like a flake8 action/workflow/job to run on changes to this repo to hopefully prevent something like this from happening in the future?

_Originally posted by @mriedem in https://github.com/fralau/mkdocs_macros_plugin/issues/106#issuecomment-976597595_
___________

@fralau 
Have a look at the workflow we're (@WoltLab) are using to test that our mkdocs documentation builds successfully:

https://github.com/WoltLab/docs.woltlab.com/blob/5.5/.github/workflows/test.yml

Just commit that file to the repository (make the necessary adjustments, e.g. for setup.py) and it will automatically be active. It detected the bad merge: https://github.com/WoltLab/docs.woltlab.com/runs/4300011035?check_suite_focus=true

Full documentation is here: https://docs.github.com/en/actions

_Originally posted by @TimWolla in https://github.com/fralau/mkdocs_macros_plugin/issues/106#issuecomment-976610153_

**Comment by Guts** [comment]
IMHO I would suggest to promote using flake8 as a git hook through precommit to allow developers check out errors before committing to the project and, optionally, run it in CI through precommit ci.

**Comment by fralau** [comment]
@Guts Thanks a lot for you kind offer for a PR, and with pleasure! 

Perhaps you could describe here (for people like me with limited knoweldge of that kind of tools) what it does... and what kind of errors it would catch, not catch, and (if there is any chance of that) erroneously catch?

**Comment by timvink** [comment]
`flake8` is great, but makes a lot of stylistic checks also. I've had it raise errors for things I don't want to 'fix'. Using it requires some work on defining which rules you want to ignore.

I recommend [`pyflakes`](https://pypi.org/project/pyflakes/), which:

> [...] will try very, very hard to never emit false positives.

It would have catched the merge conflict error in #106 : 

```shell
echo "<<<<<<< HEAD
=======
>>>>>>> new_branch_to_merge_later" > test.py
pyflakes test.py
#> test.py:1:1: invalid syntax
#> <<<<<<< HEAD
```

**Comment by Guts** [comment]
@timvink flake8 is built over pyflakes: https://github.com/PyCQA/flake8/blob/main/setup.cfg#L44

You can use flake8 to spot only a selection of errors (white-list) instead of ignoring others (black list). Let me know.

**Comment by timvink** [comment]
Yes. Just trying to help.
