### ISSUE TITLE
License of dog-eating.jpg is not free software compatible

### ISSUE THREAD

**Issue by stefanor** [fralau/mkdocs-macros-plugin#201]
Sorry to be pain, but I think [dog-eating.jpg](https://github.com/fralau/mkdocs-macros-plugin/blob/master/webdoc/docs/dog-eating.jpg) came from unsplash.com ([license](https://unsplash.com/license)) which is not sufficiently free for distribution in the Debian main archive. Unsplash used to use a CC-0 license, but they migrated to their current license before this image was added to unsplash.

Can I suggest that you replace this image with something licensed CC-0 or similar?

We're not even building the docs for mkdocs-macros-plugin in Debian right now (because it requires mermaid2), so we just stripped the file and ignored it. But I think you should be aware of the issue.

**Comment by fralau** [comment]
Good point. That seems fairly easy to correct.

If you have an idea for a replacement image, that would be welcome.

> We're not even building the docs for mkdocs-macros-plugin in Debian right now (because it requires mermaid2), so we just stripped the file and ignored it. But I think you should be aware of the issue.

Why would that be a problem?

**Comment by stefanor** [comment]
I mean that at the moment this bug isn't an issue for Debian. We can't build `mkdocs-macros-plugin`'s docs within Debian.

But we do have to remove the image from our source package, because it isn't compatible with Debian's [free software guidelines](https://www.debian.org/social_contract#guidelines)
