### ISSUE TITLE
Disable macros plugin in certain subdirectories

### ISSUE THREAD

**Issue by jonaprieto** [fralau/mkdocs-macros-plugin#214]
Is there an option I could use for the task in the title? I found myself generating a bunch of files that are not meant to be processed by this plugin.

**Comment by fralau** [comment]
Yes this is a new experimental function (see #204).

**Comment by fralau** [comment]
Or rather, this seems the dual of the other problem... 🤔 

You wish to have an **opt-out** for macro-rendering, for a directory and its subdirectories?

**Comment by fralau** [comment]
@jonaprieto Is that issue still relevant?
