### ISSUE TITLE
Project is missing py.typed marker

### ISSUE THREAD

**Issue by ssbarnea** [fralau/mkdocs-macros-plugin#219]
When adding the package, mypy complains about missing type marker.

```
src/mkdocs_ansible/__init__.py:10: error: Skipping analyzing "mkdocs_macros.plugin": module is installed, but missing library stubs or py.typed marker  [import-untyped]
src/mkdocs_ansible/__init__.py:10: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```

This can easily be sorted by just adding the `py.typed` inside the package, even before the full types are adopted by the project.

**Comment by kchr** [comment]
@fralau This scenario occurs when a developer has `mkdocs-macros-plugin` installed in their own environment, and uses `mypy` to analyze not only their own source code but also any installed/imported packages found in the project environment (in this case it seems to be a project called `mkdocs_ansible`).

The warning will be raised by `mypy` when it encounters a package that does not declare that it has type hints. This can be declared in a number of ways, one of them being to include a file called `py.typed` in the package. See the following page for instructions on how to do so, making your package compliant to the PEP 561 standard:

https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages

As the page above says:

> If you would like to publish a library package to a package repository yourself (e.g. on PyPI) for either internal or external use in type checking, packages that supply type information via type comments or annotations in the code should put a py.typed file in their package directory. For example, here is a typical directory structure:
> 
> ```
> setup.py
> package_a/
>     __init__.py
>     lib.py
>     py.typed
> ```
