### ISSUE TITLE
Macros syntax error for math equations

### ISSUE THREAD

**Issue by jonaprieto** [fralau/mkdocs-macros-plugin#221]
I have a few math equations on my markdown files, which usually require curly braces; it's LaTeX. For example, the following changes fix the error messages produced by this macro plugin: (I cannot escape these characters. Otherwise, the equation does not render well.) The error disappears after the double-curly braces pattern is removed. Again, this is not an admissible fix. 

```diff
+           $$ \cb{{\sig{\blue m}} \mid {\blue m \in \green M}} $$
-           $$ \cb{\sig{\blue m} \mid {\blue m \in \green M} $$
 ```

**Comment by fralau** [comment]
Yes, the issue of having Jinja2 accidentally mistaking some code with its own directives and attempting to translate them is unavoidable (and indeed some LateX statements one of these).

There are [5 solutions described for this problem](https://mkdocs-macros-plugin.readthedocs.io/en/latest/rendering/), depending on your circumstances, and altering the Jinja2 delimiters is one of them.
