### ISSUE TITLE
Mermaid seems to be incompatible with mkdocs-macros

### ISSUE THREAD

**Issue by SPyofgame** [fralau/mkdocs-macros-plugin#225]
With mermaid.js and html, css inside the table, I can make some visualization like this

![image](https://github.com/fralau/mkdocs-macros-plugin/assets/62207095/2212c342-2e26-4bd5-b5fc-bdb493ce106c)

But after using mkdocs-macros, I can still you mermaid.js but I can not name any nodes nor using CSS 

![image](https://github.com/fralau/mkdocs-macros-plugin/assets/62207095/71a69ee2-bbaa-4eb3-ac22-52c3b07152b9)

**Comment by SPyofgame** [comment]
Fixed, by doing something like

```md
      j2_block_start_string: '{{{%'
      j2_block_end_string: '%}}}'
      j2_variable_start_string: '{{{@'
      j2_variable_end_string: '}}}@'
      j2_comment_start_string: '{{{#'
      j2_comment_end_string: '#}}}'
```

**Comment by fralau** [comment]
Wow, what a pretty diagram! 

For our information did you identify the piece of code in Mermaid that was tripping MkDocs-Macros?

**Comment by SPyofgame200** [comment]
I don't know for sure, but I think some kind of `start_string` and `end_string` of mermaid and macros was incompatible so we must use them differently. I tried to change a few permutations of order of the plugins but it seems... ehmmmm not working I guess ?

**Comment by SPyofgame200** [comment]
> Wow, what a pretty diagram!
> 
> For our information did you identify the piece of code in Mermaid that was tripping MkDocs-Macros?

I was dedicated with my own project, in order to teach my students better, so I tried to make my site with many interactive features

**Comment by fralau** [comment]
Perhaps searching with your editor for offending strings  might help?

I am just curious about it: the question of how to ensure compatibility of Mkdocs-Macros' syntax with other plugins has been a [topic of extensive research](https://mkdocs-macros-plugin.readthedocs.io/en/latest/rendering/).

And considering that I am the author of _both_ plugins 🙂 ...
