### ISSUE TITLE
Expose relative URL fixer filter in Jinja2 environment

### ISSUE THREAD

**Issue by SuibianP** [fralau/mkdocs-macros-plugin#236]
(Discussed in https://github.com/fralau/mkdocs-macros-plugin/discussions/199)

MkDocs has the [`url`](https://www.mkdocs.org/dev-guide/themes/#url) filter (implemented [here](https://github.com/mkdocs/mkdocs/blob/62a4e3c213d4cbdb27c08d9456aaff5b583bca07/mkdocs/utils/templates.py#L37-L40) and exported [here](https://github.com/mkdocs/mkdocs/blob/62a4e3c213d4cbdb27c08d9456aaff5b583bca07/mkdocs/theme.py#L163)) that resolves relative URLs to the current page. mkdocs-macro has a similar function [`fix_url`](https://mkdocs-macros-plugin.readthedocs.io/en/latest/tips/#the-fix_url-function) which is not exported to the jinja environment.

The direct workaround is adding it to the environment in `define_env` as mentioned [here](https://github.com/fralau/mkdocs-macros-plugin/discussions/199#discussioncomment-7802759). Nonetheless, as this functionality is frequently used such as when constructing `href` attributes, it would be beneficial to export this by default. Preferably the filter could be named `url` as well to match mkdocs behaviour.

**Comment by fralau** [comment]
The last version on github now contains that filter, visible thanks to `{{ macros_info() }}`. 

![Capture](https://github.com/user-attachments/assets/769e2d32-a30d-4406-834e-7a9f0598577a)

@SuibianP  Could I ask you to test whether it works correctly for you?

**Comment by SuibianP** [comment]
@fralau Thanks for the addition! `"relative/url/to/base" | normalize_url(page)` works for me now.

Would it be better to take `env.page` instead of [`None`](https://github.com/mkdocs/mkdocs/blob/62a4e3c213d4cbdb27c08d9456aaff5b583bca07/mkdocs/utils/__init__.py#L205) by default, so that there is no need to repeat `page` for the most common case (relative to current page)? This is also how `url_filter` is [implemented](https://github.com/mkdocs/mkdocs/blob/62a4e3c213d4cbdb27c08d9456aaff5b583bca07/mkdocs/utils/templates.py#L40).

**Comment by fralau** [comment]
OK, I had missed that point!

Back to the drawing, board. I implemented the new filter, called `relative_url`, exactly [as implemented in the example of the discussion](199#discussioncomment-7802759).
![Capture d’écran 2024-07-28 à 16 19 40](https://github.com/user-attachments/assets/d9d49faf-42a4-4253-90e7-f042fd057c48)

**Comment by fralau** [comment]
@SuibianP Test again?

**Comment by SuibianP** [comment]
@fralau Works for me, thanks a lot!
