### ISSUE TITLE
Need a registration hook for other plugins

### ISSUE THREAD

**Issue by fralau** [fralau/mkdocs-macros-plugin#237]
As explained by @timvink in squidfunk/mkdocs-material#5933, writers of other plugins would need some hook to declare variables, macros and filters _before_ the Mkdocs-Macros is actually run.

The rule adopted is following: three methods `register_variables()`, `register_macros()` and `register_filters()`. 

To facilitate work, these three method should work **regardless of the order of declaration of plugins**.

- The other plugin is declared _before_ Mkdocs-Macros (its `on_config()` is run before `MacrosPlugin.on_config()`): they will be stored for later, and added _last_ to the list of variables, macros or filters.
- The other plugin is declared _after_: they are immediately added to the list of variables, macros or filters.

In both cases, those keys are added on top of all other ones. **Duplicate keys are not allowed and will cause a KeyError.**

**Comment by fralau** [comment]
@timvink It's written. I have tested it roughly, so that I see that the code should work; but it would take me some time to build a test case.

Would you like to see if it works for you?

**Comment by timvink** [comment]
Sure, will try next week.

At the scale mkdocs-macros is at already, sure you don't write to write a unit test for this functionality, to ensure it keeps working in the future?

**Comment by fralau** [comment]
> Sure, will try next week.
> 
> At the scale mkdocs-macros is at already, sure you don't write to write a unit test for this functionality, to ensure it keeps working in the future?

Yes. I have relied on testing my plugin on test websites (available), but I need to introduce a unit testing system.

In a few words, how do you go about unit-testing an mkdocs plugin, without using `mkdocs serve` (since it relies on MkDocs framework)?

**Comment by timvink** [comment]
You can test the functions / custom classes separately of course. I actually do prefer small 'integration' testing using `mkdocs build`. 

What's worked for me is to build up a collection of small standalone examples (like here https://github.com/timvink/mkdocs-table-reader-plugin/tree/master/tests/fixtures) and test whether they fail (sometimes they should) or succeed, and whether the resulting html page(s) contain expected output. See f.e. https://github.com/timvink/mkdocs-table-reader-plugin/blob/master/tests/test_build.py

**Comment by fralau** [comment]
@timvink  Thank you for these examples, this is very interesting!

**Comment by timvink** [comment]
Fixed it. See PR #238 

Implemented in table reader here: https://github.com/timvink/mkdocs-table-reader-plugin/pull/77

**Comment by fralau** [comment]
I passed the PR. Thanks a lot!

**Comment by fralau** [comment]
We know have a formal test in MkDocs-Macros for this development!

Which was what prompted the whole discussion about the testing framework in the first place (#244), and finally the creation of the [MkDocs-Test plugin](https://github.com/fralau/mkdocs-test)! 😮‍💨.

So we have gone full circle 🙂.
