### ISSUE TITLE
print statement left in the plugin's code? [1.2.0]

### ISSUE THREAD

**Issue by FredZinelli** [fralau/mkdocs-macros-plugin#242]
Hello,

Glad to see the 1.2 out !
Just so that you know: maybe it's intended (though, it's not using the logger), there is a print statement left in the plugin's `_load_module` method, [line 510](https://github.com/fralau/mkdocs-macros-plugin/blob/e8b3f45628ebaf8be2cb9d58a7263dd8dc3df24f/mkdocs_macros/plugin.py#L510)

Cheers

**Comment by fralau** [comment]
Thanks for the heads-up: having that kind of quality check from the user community, in addition of the other tools, helps a lot!

**Comment by timvink** [comment]
Try enabling some ruff rules on the project via GitHub actions or precommit hooks. It can auto detect those kind of issues. https://github.com/astral-sh/ruff

**Comment by fralau** [comment]
@timvink Thanks for this suggestion (ruff is a Linter). This is part of the ongoing refection on code quality assurance for this project.
