### ISSUE TITLE
"CANNOT INTERPRET" messages

### ISSUE THREAD

**Issue by websolutions-hamburg** [fralau/mkdocs-macros-plugin#247]
Hello, I get this "**CANNOT INTERPRET**" messages with `mkdocs serve`:

>❯ mkdocs serve
INFO    -  Building documentation...
INFO    -  [macros] - Macros arguments
            {'module_name': 'main', 'modules': [], 'render_by_default': True, 'force_render_paths': '', 'include_dir': '', 'include_yaml': [],
           'j2_block_start_string': '', 'j2_block_end_string': '', 'j2_variable_start_string': '', 'j2_variable_end_string': '', 'j2_comment_start_string': '',
           'j2_comment_end_string': '', 'on_undefined': 'keep', 'on_error_fail': False, 'verbose': False}
INFO    -  [macros] - No default module `main` found
INFO    -  [macros] - Config variables: ['extra', 'config', 'environment', 'plugin', 'git']
**CANNOT INTERPRET <class 'mkdocs.theme.Theme'>
CANNOT INTERPRET <class 'mkdocs_macros.plugin.MacrosPlugin'>
CANNOT INTERPRET <class 'material.plugins.search.plugin.SearchPlugin'>**
INFO    -  [macros] - Config macros: ['context', 'macros_info', 'now', 'fix_url']
INFO    -  [macros] - Config filters: ['pretty', 'relative_url']
INFO    -  Cleaning site directory
INFO    -  [macros] - Rendering source page: index.md
INFO    -  Documentation built in 0.60 seconds
INFO    -  [20:49:40] Watching paths for changes: 'docs', 'mkdocs.yml'
INFO    -  [20:49:40] Serving on http://127.0.0.1:8000/mysite/

Is this a Bug?

mkdocs.yml
```yaml
site_name: My site
site_url: https://mydomain.org/mysite
theme:
  name: material
plugins:
  - macros
  - search
```

Plugin Versions
```txt
mkdocs-material=9.5.40
mkdocs-macros-plugin=1.3.4
```

Python Version: 3.12.6

**Comment by fralau** [comment]
Hi. It's a development artifact, that should not have any impact on the operation of the module. 

Version 1.3.5 was rolled out; it should have solved the issue.

Let me know if it fixed it for you?

**Comment by websolutions-hamburg** [comment]
Perfect, it's fixed! Thanks 👍
