### ISSUE TITLE
Disable Rendering source page info messages

### ISSUE THREAD

**Issue by mhussein** [fralau/mkdocs-macros-plugin#248]
We recently updated from 1.0.5 to 1.3.5 and started seeing a lot of messages in the log, for example

```
INFO    -  [macros] - Rendering source page: index.md
INFO    -  [macros] - Rendering source page: apis.md
INFO    -  [macros] - Rendering source page: docs.md
INFO    -  [macros] - Rendering source page: tags.md
...
...
```

Is there a way to suppress those log messages?

**Comment by fralau** [comment]
Good question. We could perhaps downgrade some of these messages as DEBUG? 🤔 

Aside of these, which are the ones you find annoying?

**Comment by mhussein** [comment]
my 2c

The "Macros arguments" one feels like Debug, but it is useful, so maybe keep it as INFO, similar to the "Loading yaml file" ones.

The "Configuring the macros environment..." and "End of environment config" are useless outside debug env. Those can go.

The "config [variables|macros|filters] again feels like debug, but they are useful to discover things you can do that you may not be aware of.

**Comment by fralau** [comment]
Thanks for the feedback. I'll have a look at this.

For the context, I introduced a new testing framework (see #244), so I went a little overboard. 🙂 

In reality, the testing framework relies minimally on the log, except for reading the variables, filters and macros (but these are DEBUG entries, not INFO).

**Comment by michsien104** [comment]
This is indeed really annoying. Waiting for that fix as well.

**Comment by fralau** [comment]
@michsien104 It's good to know. 🙂

**Comment by mark-bozeman** [comment]
A fix would be great.

**Comment by fralau** [comment]
@mhussein , @michsien104, @mark-bozeman Fixed. 

Could I ask you to test whether it's fine for you now?

**Comment by mhussein** [comment]
@fralau Thanks a lot. 

1. I installed 1.3.5, ran mkdocs serve, verified that I get a ton of messages from the macros plugin.
2. Installed 1.3.6, ran mkdocs serve again, and verified that the extra messages are no longer there.

I still get those log messages, which I think is perfectly fine:

```
INFO    -  [macros] - Loading yaml file: C:\macros/dictionary.yaml
INFO    -  [macros] - No default module `main` found
INFO    -  [macros] - Config variables: ['extra', 'config', 'environment', 'plugin', 'git', 'hide', 'macros', 'filters', 'filters_builtin']
INFO    -  [macros] - Config macros: ['context', 'macros_info', 'now', 'fix_url']
INFO    -  [macros] - Config filters: ['pretty', 'relative_url']
```

**Comment by fralau** [comment]
@mhussein Thanks a lot!
