### ISSUE TITLE
Mistake in the docs (jinja comment blocks)

### ISSUE THREAD

**Issue by FredZinelli** [fralau/mkdocs-macros-plugin#252]
Hello,

There are 2 typos in the [config page](https://mkdocs-macros-plugin.readthedocs.io/en/latest/#configuration-of-the-plugin), where the text is talking about variables instead of comments, and talking about end instead of start:

![image](https://github.com/user-attachments/assets/3ce41581-e58b-448c-9d42-6978799e3a77)

(...I just found the same kind of problem in my own documentation... :rofl: )

Cheers

---

edit: btw, the version number of the plugin in the docs is still showing up as 1.0.4 (top right corner)

**Comment by fralau** [comment]
I also created a new release to get a more up-to-date version in the top right corner.
